### PR TITLE
NullPointerException while creating Picture Message

### PR DESCRIPTION
**Pull request by gitlabbin**
fix for issue #67

### CODE REVIEW

**Comment by bassaer** [comment]
@gitlabbin 
Thanks!

**Comment by dsfjd** [comment]
First of all thank you for you fast help :+1: !, the fix is working but only if i use @gitlabbin repo with his example Application but i want to use it in my own App according to your tutorial . Is it possible to update the MessageAdapter in @bassaer 's master branch I think my Project uses your master branch where the MessageAdapter isnt fixed or is there a way to use bassaer:develop branch instead of bassaer:master ?

**Comment by bassaer** [comment]
@dsfjd 
now you can use v1.5.4, please update.
enjoy!

**Comment by dsfjd** [comment]
You are awesome dude really thanks alot!


Am 17.11.2017 17:15 schrieb "Tsubasa Nakayama" <notifications@github.com>:

**Pull request merged**
