### PR TITLE
updates and fixes

### PR DESCRIPTION
**Pull request by bmx666**
- update compile and target SDK to API 27
- update support and deps libraries
- fix warn and compile error

### CODE REVIEW

**Comment by bassaer** [comment]
@bmx666 
Thanks 👍 
let me check.

**Comment by bmx666** [comment]
This project is dead?

**Comment by bassaer** [comment]
@bmx666 
Thank you for your support!

sorry for late reply.
this pull request will be merged soon.

**Comment by bmx666** [comment]
@bassaer 
Thanks for response! I just back to support my old project and update all deps of this project.
Only one warn, after migrating on AndroidX many old project would not compiled without updating **gradle.properties**
See [Migrating to AndroidX](https://developer.android.com/jetpack/androidx/migrate)

**Pull request merged**
